#!/usr/bin/env python3
"""
add_episode.py — Publishes a new episode of the "Highlights IA — MedTech
Community AI" podcast.

Pipeline:
  1. Reads the local M4A file generated by the daily scheduled task.
  2. Probes duration and size with ffprobe.
  3. Uploads the M4A to Cloudflare R2 (S3-compatible) with the correct
     Content-Type (audio/mp4) and inline Content-Disposition — making the
     file streamable by Spotify, Apple Podcasts, and any podcast client.
  4. Inserts a new <item> at the top of feed.xml inside the GitHub repo
     (via Contents API), preserving previous items.
  5. Updates episodes.json with metadata.
  6. Commits feed.xml + episodes.json via the GitHub API.

Usage:
  python add_episode.py \
    --m4a /path/to/highlights-ia-2026-05-19-podcast.m4a \
    --title "Highlights IA — 19 de maio de 2026" \
    --description "Resumo dos destaques de IA do dia..." \
    --date 2026-05-19

Required env vars (set by the scheduled task):
  GITHUB_TOKEN       — Personal Access Token with `Contents: Read and Write`
  GITHUB_OWNER       — e.g. Docgabtxsmed
  GITHUB_REPO        — e.g. medtech-highlights-ia-feed
  R2_ACCESS_KEY_ID   — Cloudflare R2 access key
  R2_SECRET_ACCESS_KEY — Cloudflare R2 secret
  R2_ENDPOINT        — e.g. https://<account_id>.r2.cloudflarestorage.com
  R2_BUCKET          — e.g. medtech-podcast
  R2_PUBLIC_URL      — e.g. https://pub-<id>.r2.dev (no trailing slash)

Optional env vars:
  PODCAST_FEED_BASE — public base URL of the feed (default:
                      https://<owner>.github.io/<repo>)
"""

from __future__ import annotations
import argparse
import base64
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path
from xml.sax.saxutils import escape

import urllib.request
import urllib.error


# ============================================================
#  Helpers
# ============================================================

def http(method: str, url: str, token: str,
         data: bytes | None = None,
         content_type: str = "application/json",
         extra_headers: dict | None = None) -> tuple[int, bytes]:
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("User-Agent", "highlights-ia-publisher/2.0")
    if data is not None:
        req.add_header("Content-Type", content_type)
    if extra_headers:
        for k, v in extra_headers.items():
            req.add_header(k, v)
    try:
        with urllib.request.urlopen(req) as r:
            return r.status, r.read()
    except urllib.error.HTTPError as e:
        return e.code, e.read()


def ffprobe_duration_seconds(path: Path) -> int:
    out = subprocess.check_output([
        "ffprobe", "-v", "error",
        "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(path)
    ]).decode().strip()
    return int(round(float(out)))


def hhmmss(total: int) -> str:
    h, rem = divmod(total, 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"


def load_dotenv(path: Path) -> dict:
    """Read simple KEY=value lines (no quoting) from a credentials file."""
    out = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


# ============================================================
#  Cloudflare R2 upload (S3-compatible)
# ============================================================

def upload_to_r2(m4a_path: Path,
                 object_key: str,
                 access_key: str,
                 secret_key: str,
                 endpoint: str,
                 bucket: str) -> None:
    """Upload the audio file to R2 with proper podcast headers."""
    try:
        import boto3
        from botocore.config import Config
    except ImportError:
        print("ERROR: boto3 not installed. Run: "
              "pip3 install boto3 --break-system-packages",
              file=sys.stderr)
        sys.exit(2)

    s3 = boto3.client(
        "s3",
        endpoint_url=endpoint,
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        region_name="auto",
        config=Config(signature_version="s3v4", retries={"max_attempts": 3}),
    )

    extra = {
        "ContentType": "audio/mp4",
        "ContentDisposition": f'inline; filename="{m4a_path.name}"',
        "CacheControl": "public, max-age=31536000",  # 1 year
    }

    print(f"  Uploading {m4a_path.name} ({m4a_path.stat().st_size:,} bytes) to R2...")
    with open(m4a_path, "rb") as f:
        s3.put_object(
            Bucket=bucket,
            Key=object_key,
            Body=f,
            **extra,
        )


# ============================================================
#  GitHub Contents API (feed.xml / episodes.json updates)
# ============================================================

def get_file(owner: str, repo: str, token: str, path: str) -> dict:
    url = f"https://api.github.com/repos/{owner}/{repo}/contents/{path}"
    status, content = http("GET", url, token)
    if status >= 300:
        raise RuntimeError(f"get_file {path} {status}: {content.decode()[:400]}")
    return json.loads(content)


def put_file(owner: str, repo: str, token: str, path: str,
             new_bytes: bytes, message: str, sha: str | None = None) -> dict:
    url = f"https://api.github.com/repos/{owner}/{repo}/contents/{path}"
    body = {
        "message": message,
        "content": base64.b64encode(new_bytes).decode(),
        "committer": {
            "name": "highlights-ia-bot",
            "email": "gabrieltavaresx@gmail.com"
        }
    }
    if sha:
        body["sha"] = sha
    status, content = http("PUT", url, token,
                            data=json.dumps(body).encode())
    if status >= 300:
        raise RuntimeError(f"put_file {path} {status}: {content.decode()[:400]}")
    return json.loads(content)


# ============================================================
#  Feed manipulation
# ============================================================

def build_item_xml(title: str, description: str, link: str,
                   enclosure_url: str, length_bytes: int,
                   pub_dt: datetime, duration_sec: int,
                   guid: str, cover_url: str) -> str:
    return f"""    <item>
      <title>{escape(title)}</title>
      <description><![CDATA[{description}]]></description>
      <link>{escape(link)}</link>
      <guid isPermaLink="false">{escape(guid)}</guid>
      <pubDate>{format_datetime(pub_dt)}</pubDate>
      <enclosure url="{escape(enclosure_url)}" length="{length_bytes}" type="audio/mp4"/>
      <itunes:author>Gabriel Tavares</itunes:author>
      <itunes:duration>{hhmmss(duration_sec)}</itunes:duration>
      <itunes:summary><![CDATA[{description}]]></itunes:summary>
      <itunes:image href="{escape(cover_url)}"/>
      <itunes:explicit>false</itunes:explicit>
      <itunes:episodeType>full</itunes:episodeType>
    </item>"""


def insert_item(feed_xml: str, item_xml: str) -> str:
    marker = "    <!-- ITEMS_INSERT_HERE -->"
    if marker in feed_xml:
        return feed_xml.replace(marker, item_xml + "\n" + marker, 1)
    return feed_xml.replace("</channel>", item_xml + "\n  </channel>", 1)


# ============================================================
#  Main
# ============================================================

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--m4a", required=True, type=Path)
    ap.add_argument("--title", required=True)
    ap.add_argument("--description", required=True)
    ap.add_argument("--date", required=True, help="YYYY-MM-DD (publication date)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Build XML and print what would be done, but do not call GitHub/R2.")
    args = ap.parse_args()

    # ---- Load R2 credentials from file if env vars are missing ----
    creds_file = Path.home() / ".medtech-secrets" / "r2-credentials"
    if creds_file.exists():
        for k, v in load_dotenv(creds_file).items():
            os.environ.setdefault(k, v)

    token = os.environ.get("GITHUB_TOKEN")
    owner = os.environ.get("GITHUB_OWNER", "Docgabtxsmed")
    repo  = os.environ.get("GITHUB_REPO", "medtech-highlights-ia-feed")
    base_public = os.environ.get(
        "PODCAST_FEED_BASE",
        f"https://{owner.lower()}.github.io/{repo}"
    )

    r2_access = os.environ.get("R2_ACCESS_KEY_ID")
    r2_secret = os.environ.get("R2_SECRET_ACCESS_KEY")
    r2_endpoint = os.environ.get("R2_ENDPOINT")
    r2_bucket = os.environ.get("R2_BUCKET", "medtech-podcast")
    r2_public_url = os.environ.get("R2_PUBLIC_URL", "").rstrip("/")

    if not args.m4a.exists():
        print(f"ERROR: m4a not found: {args.m4a}", file=sys.stderr)
        sys.exit(2)

    size_bytes = args.m4a.stat().st_size
    duration = ffprobe_duration_seconds(args.m4a)
    pub_dt = datetime.fromisoformat(args.date).replace(
        hour=10, minute=0, tzinfo=timezone.utc
    )
    guid = f"episode-{args.date}"
    link = f"{base_public}/episodes/{args.date}"
    cover_url = f"{base_public}/cover.png"
    object_key = args.m4a.name  # store at bucket root
    enclosure_url = f"{r2_public_url}/{object_key}" if r2_public_url else "(unset)"

    print(f"Episode: {args.title}")
    print(f"  date={args.date}  size={size_bytes}B  duration={hhmmss(duration)}")
    print(f"  R2 object: {object_key}")
    print(f"  enclosure URL: {enclosure_url}")

    if args.dry_run:
        print("[DRY-RUN] skipping R2 upload and GitHub calls")
        item_xml = build_item_xml(
            args.title, args.description, link,
            enclosure_url, size_bytes, pub_dt, duration,
            guid, cover_url
        )
        print("--- generated <item> ---")
        print(item_xml)
        return

    # ---- Validate credentials ----
    missing = []
    if not token: missing.append("GITHUB_TOKEN")
    if not r2_access: missing.append("R2_ACCESS_KEY_ID")
    if not r2_secret: missing.append("R2_SECRET_ACCESS_KEY")
    if not r2_endpoint: missing.append("R2_ENDPOINT")
    if not r2_public_url: missing.append("R2_PUBLIC_URL")
    if missing:
        print(f"ERROR: missing env vars: {', '.join(missing)}", file=sys.stderr)
        sys.exit(2)

    # ---- 1) Upload to R2 ----
    print("Uploading to Cloudflare R2...")
    upload_to_r2(args.m4a, object_key,
                 r2_access, r2_secret, r2_endpoint, r2_bucket)
    print(f"  done: {enclosure_url}")

    # ---- 2) Fetch current feed.xml + episodes.json from GitHub ----
    print("Fetching current feed.xml + episodes.json...")
    feed_meta = get_file(owner, repo, token, "feed.xml")
    ep_meta   = get_file(owner, repo, token, "episodes.json")
    feed_xml = base64.b64decode(feed_meta["content"]).decode("utf-8")
    eps_data = json.loads(base64.b64decode(ep_meta["content"]).decode("utf-8"))

    # Idempotency: if guid already present, skip feed update
    if any(e.get("guid") == guid for e in eps_data.get("episodes", [])):
        print(f"Episode {guid} already in feed — skipping feed update "
              f"(R2 upload above did overwrite the file).")
        print(f"DONE — feed remains at {base_public}/feed.xml")
        return

    # ---- 3) Build new <item> and inject ----
    item_xml = build_item_xml(
        args.title, args.description, link,
        enclosure_url, size_bytes, pub_dt, duration,
        guid, cover_url
    )
    new_feed = insert_item(feed_xml, item_xml)

    # ---- 4) Update episodes.json (newest first) ----
    eps_data.setdefault("episodes", []).insert(0, {
        "guid": guid,
        "date": args.date,
        "title": args.title,
        "duration_seconds": duration,
        "size_bytes": size_bytes,
        "enclosure_url": enclosure_url,
        "object_key": object_key,
    })

    # ---- 5) Push both files ----
    print("Pushing feed.xml...")
    put_file(owner, repo, token, "feed.xml",
             new_feed.encode("utf-8"),
             message=f"Add episode {args.date}",
             sha=feed_meta["sha"])
    print("Pushing episodes.json...")
    put_file(owner, repo, token, "episodes.json",
             json.dumps(eps_data, indent=2, ensure_ascii=False).encode("utf-8"),
             message=f"Update episodes.json for {args.date}",
             sha=ep_meta["sha"])

    print(f"DONE — feed updated at {base_public}/feed.xml")
    print(f"Audio served from {enclosure_url}")
    print(f"Spotify should pull within ~10-30 minutes.")


if __name__ == "__main__":
    main()
