#!/usr/bin/env python3
"""
add_episode.py — Publishes a new episode of the "Highlights IA — MedTech
Community AI" podcast.

Pipeline:
  1. Reads the local M4A file generated by the daily scheduled task.
  2. Probes duration and size with ffprobe.
  3. Creates a GitHub Release (tag: episode-YYYY-MM-DD) and uploads the M4A
     as an asset, using the GitHub REST API (no `gh` CLI required).
  4. Inserts a new <item> at the top of feed.xml inside the local clone of
     the repo, preserving previous items.
  5. Updates episodes.json with metadata.
  6. Commits and pushes feed.xml + episodes.json via the GitHub API
     contents endpoint (one PUT per file — no local git needed).

Usage:
  python add_episode.py \
    --m4a /path/to/highlights-ia-2026-05-19-podcast.m4a \
    --title "Highlights IA — 19 de maio de 2026" \
    --description "Resumo dos destaques de IA do dia..." \
    --date 2026-05-19

Required env vars:
  GITHUB_TOKEN  — Personal Access Token with `repo` scope
  GITHUB_OWNER  — e.g. gabrieltavaresx
  GITHUB_REPO   — e.g. medtech-highlights-ia-feed

Optional env vars:
  PODCAST_FEED_BASE — public base URL (default:
                      https://<owner>.github.io/<repo>)
"""

from __future__ import annotations
import argparse
import base64
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path
from xml.sax.saxutils import escape

import urllib.request
import urllib.error


# ---------------- helpers ----------------

def http(method: str, url: str, token: str,
         data: bytes | None = None,
         content_type: str = "application/json",
         extra_headers: dict | None = None) -> tuple[int, bytes]:
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("User-Agent", "highlights-ia-publisher/1.0")
    if data is not None:
        req.add_header("Content-Type", content_type)
    if extra_headers:
        for k, v in extra_headers.items():
            req.add_header(k, v)
    try:
        with urllib.request.urlopen(req) as r:
            return r.status, r.read()
    except urllib.error.HTTPError as e:
        return e.code, e.read()


def ffprobe_duration_seconds(path: Path) -> int:
    out = subprocess.check_output([
        "ffprobe", "-v", "error",
        "-show_entries", "format=duration",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(path)
    ]).decode().strip()
    return int(round(float(out)))


def hhmmss(total: int) -> str:
    h, rem = divmod(total, 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"


# ---------------- GitHub Release ----------------

def create_release(owner: str, repo: str, token: str,
                   tag: str, name: str, body: str) -> dict:
    url = f"https://api.github.com/repos/{owner}/{repo}/releases"
    payload = json.dumps({
        "tag_name": tag,
        "name": name,
        "body": body,
        "draft": False,
        "prerelease": False
    }).encode()
    status, content = http("POST", url, token, data=payload)
    if status >= 300:
        raise RuntimeError(f"create_release {status}: {content.decode()[:400]}")
    return json.loads(content)


def upload_asset(upload_url_template: str, token: str,
                 m4a_path: Path) -> dict:
    # upload_url is in the form ".../assets{?name,label}" — strip the template
    base = upload_url_template.split("{")[0]
    filename = m4a_path.name
    url = f"{base}?name={filename}"
    with open(m4a_path, "rb") as f:
        data = f.read()
    status, content = http("POST", url, token,
                            data=data, content_type="audio/mp4")
    if status >= 300:
        raise RuntimeError(f"upload_asset {status}: {content.decode()[:400]}")
    return json.loads(content)


# ---------------- File update via Contents API ----------------

def get_file(owner: str, repo: str, token: str, path: str) -> dict:
    url = f"https://api.github.com/repos/{owner}/{repo}/contents/{path}"
    status, content = http("GET", url, token)
    if status >= 300:
        raise RuntimeError(f"get_file {path} {status}: {content.decode()[:400]}")
    return json.loads(content)


def put_file(owner: str, repo: str, token: str, path: str,
             new_bytes: bytes, message: str, sha: str | None = None) -> dict:
    url = f"https://api.github.com/repos/{owner}/{repo}/contents/{path}"
    body = {
        "message": message,
        "content": base64.b64encode(new_bytes).decode(),
        "committer": {
            "name": "highlights-ia-bot",
            "email": "gabrieltavaresx@gmail.com"
        }
    }
    if sha:
        body["sha"] = sha
    status, content = http("PUT", url, token,
                            data=json.dumps(body).encode())
    if status >= 300:
        raise RuntimeError(f"put_file {path} {status}: {content.decode()[:400]}")
    return json.loads(content)


# ---------------- Feed manipulation ----------------

def build_item_xml(title: str, description: str, link: str,
                   enclosure_url: str, length_bytes: int,
                   pub_dt: datetime, duration_sec: int,
                   guid: str, cover_url: str) -> str:
    return f"""    <item>
      <title>{escape(title)}</title>
      <description><![CDATA[{description}]]></description>
      <link>{escape(link)}</link>
      <guid isPermaLink="false">{escape(guid)}</guid>
      <pubDate>{format_datetime(pub_dt)}</pubDate>
      <enclosure url="{escape(enclosure_url)}" length="{length_bytes}" type="audio/mp4"/>
      <itunes:author>Gabriel Tavares</itunes:author>
      <itunes:duration>{hhmmss(duration_sec)}</itunes:duration>
      <itunes:summary><![CDATA[{description}]]></itunes:summary>
      <itunes:image href="{escape(cover_url)}"/>
      <itunes:explicit>false</itunes:explicit>
      <itunes:episodeType>full</itunes:episodeType>
    </item>"""


def insert_item(feed_xml: str, item_xml: str) -> str:
    marker = "    <!-- ITEMS_INSERT_HERE -->"
    if marker in feed_xml:
        return feed_xml.replace(marker, item_xml + "\n" + marker, 1)
    # fallback — insert before </channel>
    return feed_xml.replace("</channel>", item_xml + "\n  </channel>", 1)


# ---------------- Main ----------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--m4a", required=True, type=Path)
    ap.add_argument("--title", required=True)
    ap.add_argument("--description", required=True)
    ap.add_argument("--date", required=True, help="YYYY-MM-DD (publication date)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Build XML and print what would be done, but do not call GitHub.")
    args = ap.parse_args()

    token = os.environ.get("GITHUB_TOKEN")
    owner = os.environ.get("GITHUB_OWNER", "Docgabtxsmed")
    repo  = os.environ.get("GITHUB_REPO", "medtech-highlights-ia-feed")
    base_public = os.environ.get(
        "PODCAST_FEED_BASE",
        f"https://{owner}.github.io/{repo}"
    )

    if not args.m4a.exists():
        print(f"ERROR: m4a not found: {args.m4a}", file=sys.stderr)
        sys.exit(2)

    size_bytes = args.m4a.stat().st_size
    duration = ffprobe_duration_seconds(args.m4a)
    pub_dt = datetime.fromisoformat(args.date).replace(
        hour=10, minute=0, tzinfo=timezone.utc
    )
    tag = f"episode-{args.date}"
    guid = tag
    link = f"{base_public}/episodes/{args.date}"
    cover_url = f"{base_public}/cover.png"

    print(f"Episode: {args.title}")
    print(f"  date={args.date}  size={size_bytes}B  duration={hhmmss(duration)}")

    if args.dry_run:
        print("[DRY-RUN] skipping GitHub calls")
        enclosure = f"{base_public}/dry-run-asset/{args.m4a.name}"
        item_xml = build_item_xml(
            args.title, args.description, link,
            enclosure, size_bytes, pub_dt, duration,
            guid, cover_url
        )
        print("--- generated <item> ---")
        print(item_xml)
        return

    if not token:
        print("ERROR: GITHUB_TOKEN env var not set", file=sys.stderr)
        sys.exit(2)

    # 1) GitHub Release
    print("Creating release...")
    release = create_release(
        owner, repo, token, tag,
        name=args.title,
        body=args.description
    )
    print(f"  release id={release['id']}")

    print("Uploading asset...")
    asset = upload_asset(release["upload_url"], token, args.m4a)
    enclosure_url = asset["browser_download_url"]
    print(f"  asset url={enclosure_url}")

    # 2) Fetch current feed.xml + episodes.json
    print("Fetching current feed.xml + episodes.json...")
    feed_meta = get_file(owner, repo, token, "feed.xml")
    ep_meta   = get_file(owner, repo, token, "episodes.json")
    feed_xml = base64.b64decode(feed_meta["content"]).decode("utf-8")
    eps_data = json.loads(base64.b64decode(ep_meta["content"]).decode("utf-8"))

    # Idempotency: if guid already present, skip
    if any(e.get("guid") == guid for e in eps_data.get("episodes", [])):
        print(f"Episode {guid} already published — skipping feed update.")
        return

    # 3) Build new <item> and inject
    item_xml = build_item_xml(
        args.title, args.description, link,
        enclosure_url, size_bytes, pub_dt, duration,
        guid, cover_url
    )
    new_feed = insert_item(feed_xml, item_xml)

    # 4) Update episodes.json (newest first)
    eps_data.setdefault("episodes", []).insert(0, {
        "guid": guid,
        "date": args.date,
        "title": args.title,
        "duration_seconds": duration,
        "size_bytes": size_bytes,
        "enclosure_url": enclosure_url
    })

    # 5) Push both files
    print("Pushing feed.xml...")
    put_file(owner, repo, token, "feed.xml",
             new_feed.encode("utf-8"),
             message=f"Add episode {args.date}",
             sha=feed_meta["sha"])
    print("Pushing episodes.json...")
    put_file(owner, repo, token, "episodes.json",
             json.dumps(eps_data, indent=2, ensure_ascii=False).encode("utf-8"),
             message=f"Update episodes.json for {args.date}",
             sha=ep_meta["sha"])

    print(f"DONE — feed updated at {base_public}/feed.xml")
    print(f"Spotify should pull within ~10-30 minutes.")


if __name__ == "__main__":
    main()
